import { Geist, Geist_Mono } from "next/font/google";
import {AuthProvider} from "@/app/context/AuthContext"
import { TweetsProvider } from "./context/TweetsContext";
import "./globals.css";

// to share UI elemnts across pages/
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-fill antialiased`}
    >
      <body className="w.fill over-flow-hidden min-[330px]:w-fill
      flex justify-center items-center">
        <main className="w-[90vw] max-[550px]:w-fill h-[90vh] flex justify-center">       
          <AuthProvider>
            <TweetsProvider>
              {children}
              </TweetsProvider>
              </AuthProvider>
        </main>
      </body>
    </html>
  );
}
