import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// to share UI elemnts across pages
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body className="flex justify-center items-center">
        <main className="w-[80%]">
          {children}
        </main>
      </body>
    </html>
  );
}
